name: netguru_values_generator
description: Netguru Values generator app created for recrutment purpose.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  logger: ^0.9.4

  # UI
  custom_splash: 0.0.2
  carousel_slider: ^3.0.0
  flutter_keyboard_visibility: ^4.0.3
  keyboard_dismisser: ^1.0.2

  # Storage
  shared_preferences: 0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  build_runner: 1.11.1
  flutter_launcher_icons: 0.8.1
  flutter_launcher_name: 0.0.1
  flutter_neumorphic:
    git:
      url: https://github.com/coredeveloper/flutter-neumorphic.git
      ref: cleanup

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter_launcher_name:
  name: "Netguru VG"

flutter:
  uses-material-design: true
  assets:
     - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Black.ttf
        - asset: assets/fonts/Orbitron-ExtraBold.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-SemiBold.ttf

