name: quotes_generator
description: Quotes generator app created as a sample app..

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  logger: ^0.9.4

  # UI
  custom_splash: 0.0.2
  carousel_slider: ^3.0.0
  flutter_keyboard_visibility: ^4.0.3
  keyboard_dismisser: ^1.0.2
  after_layout: ^1.0.7+2

  # Storage
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+3
  path: ^1.7.0

  # STATE MANAGEMENT
  flutter_bloc: ^6.1.2
  path_provider: ^1.6.24
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  build_runner: 1.11.1
  flutter_launcher_icons: 0.8.1
  flutter_launcher_name: 0.0.1
  flutter_neumorphic:
    git:
      url: https://github.com/coredeveloper/flutter-neumorphic.git
      ref: cleanup

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/ic_launcher_android.png"
  image_path_ios: "assets/images/ic_launcher_iOS.png"


flutter_launcher_name:
  name: "Value Generator"

flutter:
  uses-material-design: true
  assets:
     - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Black.ttf
        - asset: assets/fonts/Orbitron-ExtraBold.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
        - asset: assets/fonts/Orbitron-Medium.ttf
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-SemiBold.ttf

